name: untyped-lambda-calc

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - OverloadedStrings

library:
  source-dirs: .
  dependencies:
    - base
    - containers
    - lexer-applicative
    - parsec
    - regex-applicative
    - srcloc
    - text
    - wl-pprint-text
